//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int event_ID { get; set; }
        public int user_ID { get; set; }
        public bool isModerator { get; set; }
        public string type { get; set; }
        public bool hasCanceled { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
